// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/documents": {
            "get": {
                "description": "Get all documents",
                "produces": [
                    "application/json"
                ],
                "summary": "Get documents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Document"
                            }
                        }
                    }
                }
            }
        },
        "/documents/{id}/approve": {
            "post": {
                "description": "Approve a document",
                "summary": "Approve a document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Document ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/documents/{id}/reject": {
            "post": {
                "description": "Reject a document",
                "summary": "Reject a document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Document ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/documents/upload": {
            "post": {
                "description": "Upload and process a document file",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Upload a document",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Document file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Document"
                        }
                    }
                }
            }
        },
        "/documents/{id}": {
            "get": {
                "description": "Get document details by ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Get a document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Document ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Document"
                        }
                    }
                }
            },
            "put": {
                "description": "Update document details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Update a document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Document ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Document data",
                        "name": "document",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Document"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Document"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Document": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "document_number": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "issue_date": {
                    "type": "string"
                },
                "issues": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ValidationIssue"
                    }
                },
                "line_items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.LineItem"
                    }
                },
                "status": {
                    "$ref": "#/definitions/model.DocumentStatus"
                },
                "subtotal": {
                    "type": "number"
                },
                "supplier_name": {
                    "type": "string"
                },
                "tax": {
                    "type": "number"
                },
                "total": {
                    "type": "number"
                },
                "type": {
                    "$ref": "#/definitions/model.DocumentType"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.DocumentStatus": {
            "type": "string",
            "enum": [
                "uploaded",
                "needs_review",
                "validated",
                "rejected"
            ],
            "x-enum-varnames": [
                "StatusUploaded",
                "StatusNeedsReview",
                "StatusValidated",
                "StatusRejected"
            ]
        },
        "model.DocumentType": {
            "type": "string",
            "enum": [
                "invoice",
                "purchase_order"
            ],
            "x-enum-varnames": [
                "TypeInvoice",
                "TypePurchaseOrder"
            ]
        },
        "model.line_items": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "total": {
                    "type": "number"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "model.ValidationIssue": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Smart Document Processing System API",
	Description:      "A system for processing business documents with data extraction and validation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
